// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1wGbQ3MHagLJGtF8Fh0XGKL7JV9pUXgg',
    appId: '1:442020185980:web:1806b9c7786ff300a646f9',
    messagingSenderId: '442020185980',
    projectId: 'mood-journal-05',
    authDomain: 'mood-journal-05.firebaseapp.com',
    storageBucket: 'mood-journal-05.firebasestorage.app',
    measurementId: 'G-7EWTEQ37XJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQNq0jla0eAxdBvjFI7zVpkUnJ8mwpZIo',
    appId: '1:442020185980:android:95642d86d565c65ca646f9',
    messagingSenderId: '442020185980',
    projectId: 'mood-journal-05',
    storageBucket: 'mood-journal-05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKy3FRZCalN_RK1nqDtHizbawhc30NVDU',
    appId: '1:442020185980:ios:8f13148299d298bba646f9',
    messagingSenderId: '442020185980',
    projectId: 'mood-journal-05',
    storageBucket: 'mood-journal-05.firebasestorage.app',
    iosClientId: '442020185980-ear50ckgbohk7ahd2uc7i6q38b2e7s56.apps.googleusercontent.com',
    iosBundleId: 'com.example.moodJournal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKy3FRZCalN_RK1nqDtHizbawhc30NVDU',
    appId: '1:442020185980:ios:8f13148299d298bba646f9',
    messagingSenderId: '442020185980',
    projectId: 'mood-journal-05',
    storageBucket: 'mood-journal-05.firebasestorage.app',
    iosClientId: '442020185980-ear50ckgbohk7ahd2uc7i6q38b2e7s56.apps.googleusercontent.com',
    iosBundleId: 'com.example.moodJournal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1wGbQ3MHagLJGtF8Fh0XGKL7JV9pUXgg',
    appId: '1:442020185980:web:56d2f988d3d84554a646f9',
    messagingSenderId: '442020185980',
    projectId: 'mood-journal-05',
    authDomain: 'mood-journal-05.firebaseapp.com',
    storageBucket: 'mood-journal-05.firebasestorage.app',
    measurementId: 'G-LQ6VWL36RM',
  );
}
